config/routes.rb
Rails.application.routes.draw do
  namespace :manage do
    resources :users
  end
  resources :user_types

  get 'welcome_user/index'
  devise_for :users , :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  root 'welcome_user#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :userType
  accepts_nested_attributes_for :userType

   # ensure user account is active
  def active_for_authentication?
    super && isActive
  end

  # provide a custom message for a inactive account
  def inactive_message
    isActive ? super : :inative_account
  end

end

app/models/user_type.rb
class UserType < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  respond_to :html, :json
  responders :flash

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
    devise_parameter_sanitizer. permit(:sign_in, keys: [:email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation, :current_password])
  end
end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController

  layout "user"

  before_action :set_user_type, only: [:show, :edit, :update, :destroy]

  def index
    @user_types = UserType.all.page(params[:page]).per(6)

    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
    
  end

  def show
  end

  def new
    @user_type = UserType.new
  end

  def edit
  end

  def create
    @user_type = UserType.new(user_type_params)

    if @user_type.save
      respond_with(@user_type, :location => user_types_url)
    else
        render :new
    end
  end

  def update
    if @user_type.update(user_type_params)
      respond_with(@user_type, :location => user_types_url)
    else
        render :edit
      end
  end

  def destroy
    @user_type.destroy
      respond_with(@user_type, :location => user_types_url)
  end

  private
    def set_user_type
      @user_type = UserType.find(params[:id])
    end

    def user_type_params
      params.require(:user_type).permit(:name, :description, :authorizeDiscount, :commissionPercentage)
    end
    def  flash_interpolation_options
      { resource_name:  @user_type .name}
    end
end

app/controllers/welcome_user_controller.rb
class WelcomeUserController < ApplicationController
  layout "user"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_boolean(boolean)
    boolean ? t('bool_yes') : t('bool_no')

  end
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/welcome_user_helper.rb
module WelcomeUserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bogeyman</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'user', media: 'all'%>
  <%= javascript_include_tag 'user'%>
</head>

<body>
    <%= yield %>
</body>
</html>

app/views/user_types/_form.html.erb
  <%= form_for(@user_type) do |f| %>
  <% if @user_type.errors.any? %>

  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4><%= pluralize(@user_type.errors.count, 'erro') %>
      <%= t("prevent", count: @user_type.errors.count) %>
      <%=t :of_save %>.
    </h4>
    <ul>
      <% @user_type.errors.full_messages.each do |message| %>
      <li><%= message %>.</li>
      <% end %>
    </ul>
  </div>

  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :authorizeDiscount %>
    <%= f.check_box :authorizeDiscount, class:"checkbox" %>
  </div>
  <div class="form-group">
    <%= f.label :commissionPercentage %><br>
    <%= f.number_field :commissionPercentage,step: 0.5, class:"form-control" %>
  </div>
  <div class="actions">
    <%= button_tag( :class => "btn btn-success") do %>
    <i class="fa fa-save"></i>
    <%=t :save %>
    <% end %>
    <%= link_to user_types_path, class: "btn btn-default" do %>
    <i class="fa fa-ban"></i>
    <%=t :cancel %>
    <% end %>
  </div>
  <% end %>

app/views/user_types/_userTypes.html.erb
<table id="userType_table" class="table table-hover table-condensed">
    <thead>
    
      <tr>
        <th>
          <%= UserType.human_attribute_name("name")%>
        </th>
        <th>
          <%= UserType.human_attribute_name("description")%>
        </th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @user_types.each do |user_type| %>
        <tr>
        <td>
          <%= user_type.name.first(40) %>
        </td>
        <td>
          <%= user_type.description.first(60) %>
        </td>
        <td>
          <%= link_to user_type, class: "btn btn-primary" do %>
          <i class="fa fa-eye"></i>
          <%= t(:show) %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_user_type_path(user_type), class: "btn btn-default" do %>
          <i class="fa fa-edit"></i>
          <%= t(:edit) %>
          <% end %>
        </td>
        <td>
          <%= link_to user_type, method: :delete, data: { confirm: t('links.are_you_sure') } , class: "btn btn-danger" do %>
          <i class="fa fa-trash"></i>
          <%= t(:delete) %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div align='right'>
        <%= page_entries_info @user_types %>
  </div>

  

app/views/user_types/edit.html.erb
<div class="container">
<h3><%= t('views.user_type.edit_user_type') %></h1>
<%= render 'form' %>

app/views/user_types/index.html.erb
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= t("activerecord.models.user_type", count: @user_types.count) %></h1>
                </div>
              </div>
    <table class="table table-condensed">
      <thead>
        <td>
          <%= link_to new_user_type_path, class: "btn btn-success" do %>
          <i class="fa fa-plus"></i>
          <%= t(:new) %>
          <% end %>
        </td>
      </thead>
    </table>
    <div class="table-responsive">

    <div id="userTypes_details">
    <%= render 'userTypes' %>
</div>
</div>
<div id="paginator" align='center'>
    <div>
      <%= paginate @user_types, :remote=>true %>
    </div>
</div>
</div>

app/views/user_types/index.js.erb
$('#userTypes_details').html('<%= escape_javascript(raw(render 'userTypes')) %>');
$('#paginator').html('<%= escape_javascript(paginate(@user_types, :remote=>true).to_s)%>');

app/views/user_types/new.html.erb
<div class="container">
<h3><%= t('views.user_type.new_user_type') %></h1>

<%= render 'form' %>

app/views/user_types/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h3>
        <%= t("activerecord.models.user_type", count: 1) %>
      </h3>
      <div class="well">
        <p>
          <strong>
            <%= UserType.human_attribute_name("name")%>:</strong>
            <%= @user_type.name %>
          </p>
          <p>
            <strong>
              <%= UserType.human_attribute_name("description")%>:</strong>
              <%= @user_type.description %>
            </p>
            <p>
              <strong>
                <%= UserType.human_attribute_name( "authorizeDiscount")%>:</strong>
                <%=human_boolean(@user_type.authorizeDiscount)  %>
              </p>
              <p>
                <strong>
                  <%= UserType.human_attribute_name("commissionPercentage")%>:</strong>
                  <%= @user_type.commissionPercentage %>
                </p>
              </div>
              <%= link_to edit_user_type_path(@user_type), class: "btn btn-info" do %>
              <i class="fa fa-edit"></i>
              <%=t :edit %>
              <% end %>
              <%= link_to user_types_path, class: "btn btn-default" do %>
              <i class="fa fa-arrow-left"></i>
              <%=t :back %>
              <% end %>
    </div>
  </div>
</div>

app/views/users/_links.erb
<% ActiveSupport::Deprecation.warn "Rendering partials devise/_links.erb is deprecated" \
  "please use devise/shared/_links.erb instead."%>
<%= render "shared/links" %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
<%= link_to t(".sign_in", :default => "Sign in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to t(".sign_up", :default => "Sign up"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
<%= link_to t(".forgot_your_password", :default => "Forgot your password?"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to t('.didn_t_receive_confirmation_instructions', :default => "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to t('.didn_t_receive_unlock_instructions', :default => "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
  <%= link_to t('.sign_in_with_provider', :provider => provider.to_s.titleize, :default => "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>